from django.db import models

# Create your models here.
from django.db import models


# Create your models here.


#https://blog.csdn.net/qq_25730711/article/details/60327344  执行迁移无效的问题

class Narg(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)  # 由于Order是musql的关键字，所以不能使用这个单词，添加一个_
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)

class Napa(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)

class Nirk(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)
    
class NirS(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)
    
class cNorB(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)
    
class qNorB(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)
    
class NosZ(models.Model):
    Reaction_Stage = models.CharField("Reaction_Stage", max_length = 1000)
    Encoding_Gene  = models.CharField("Encoding_Gene", max_length  = 200)
    Enzyme_Name = models.CharField("Enzyme_Name", max_length = 500)
    Microorganism = models.CharField("Microorganism", max_length = 1000)
    Clone = models.CharField("Clone", max_length = 300)
    GenBank_ID = models.CharField("GenBank_ID", max_length = 200)
    Nucleotide_Link = models.TextField("Nucleotide_Link", max_length = 10000)
    Authors = models.CharField("Authors", max_length = 200)
    Phylum = models.CharField("Phylum", max_length = 200)
    Class = models.CharField("Class", max_length = 200)
    myOrder = models.CharField("myOrder", max_length = 200)
    Family = models.CharField("Family", max_length = 200)
    Genus = models.CharField("Genus", max_length = 200)
    Isolation_source = models.CharField("Isolation_source", max_length = 300)
    DNA_size_bp = models.CharField("DNA_size", max_length = 200)
    UniprotK = models.CharField("Uniprot_ID", max_length  = 200)
    Uniprot_Link = models.TextField("Uniprot_Link", max_length = 10000)
    Protein_ID = models.CharField("Protein_ID", max_length = 200)
    Protein_Link = models.TextField("Protein_Link", max_length = 10000)
    Length_aa = models.CharField("Length_aa", max_length = 200)
    Title = models.CharField("Title", max_length = 500)
    PMID = models.CharField("PMID", max_length = 200)
    Link = models.TextField("Link", max_length = 10000)
    Research_Link = models.TextField("Research_Link", max_length = 10000)
    Abstract = models.TextField("Abstract", max_length = 20000)
    GenFASTA = models.CharField("GenFASTA", max_length = 200)
    ProFASTA = models.CharField("ProFASTA", max_length = 200)
    
class Product(models.Model):
  Microorganism                 = models.CharField("Microorganism", max_length = 100)
  Accesion_Number               = models.CharField("Accesion_Number", max_length = 20)
  Nucleotide_Link               = models.TextField("Nucleotide_Link", max_length = 10000)
  Isolation_source              = models.CharField("Isolation_source", max_length = 500)
  Energy_Source_Electron_donor  = models.CharField("Energy_Source_Electron_donor", max_length = 500)
  Final_Product                 = models.CharField("Final_Product", max_length = 50)
  Respiration_Fermentative_Growth  = models.CharField("Respiration_Fermentative_Growth", max_length = 20) 
  Reference                     = models.CharField("Reference", max_length = 50)
  Nitrious_intermediate_consumed_reduced_Electron_acceptor = models.CharField("Nitrious_intermediate_consumed_reduced_Electron_acceptor", max_length = 20)
  Phylum                        = models.CharField("Phylum", max_length = 200)
  Class                         = models.CharField("Class", max_length = 200)
  myOrder                         = models.CharField("myOrder", max_length = 200)
  Family                        = models.CharField("Family", max_length = 200)
  Genus                         = models.CharField("Genus", max_length = 200)
  Title                         = models.TextField("Title", max_length = 5000)
  PMID                          = models.CharField("PMID", max_length = 30)
  PubMed_Link                   = models.TextField("PubMed_Link", max_length = 10000)  
  Research_Link                 = models.TextField("Research_Link", max_length = 10000)
  Abstract                      = models.TextField("Abstract", max_length = 20000)

class WaterTreatmentPlant(models.Model):
    Influent_Source_Type   = models.CharField("Influent_Source_Type", max_length = 200)
    Denitrification_System = models.CharField("Denitrification_System", max_length = 200)
    Denitrifying_Reactor   = models.CharField("Denitrifying_Reactor", max_length = 200)
    Medium                 = models.CharField("Medium", max_length = 200)
    Culture                = models.CharField("Culture", max_length = 200)
    Organism_cultured      = models.CharField("Organism_cultured", max_length = 200)
    Respiration            = models.CharField("Respiration", max_length = 200)
    Electron_Donor         = models.TextField("Electron_Donor", max_length = 2000)
    Electron_Acceptor      = models.CharField("Electron_Acceptor", max_length = 200)
    Input                  = models.CharField("Input", max_length = 200)
    Nitrate_Removal_Rate   = models.CharField("Nitrate_Removal_Rate", max_length = 200)
    Denitrification_Rate   = models.CharField("Denitrification_Rate", max_length = 200)
    Microorganism_identified = models.TextField("Microorganism_identified", max_length = 2000)
    Molecular_Tools        = models.CharField("Molecular_Tools", max_length = 200)
    Major_Findings         = models.CharField("Major_Findings", max_length = 2000)
    Authors                = models.CharField("Authors", max_length = 200)
    Title                  = models.TextField("Title", max_length = 5000)
    Pubmed                 = models.CharField("Pubmed", max_length = 2000)
    Link                   = models.CharField("Link", max_length = 200)
    Abstract               = models.TextField("Abstract", max_length = 20000)
    
class FreshwaterSystem(models.Model):
    Influent_Source_Type   = models.CharField("Influent_Source_Type", max_length = 200)
    Denitrification_System = models.CharField("Denitrification_System", max_length = 200)
    Denitrifying_Reactor   = models.CharField("Denitrifying_Reactor", max_length = 200)
    Medium                 = models.CharField("Medium", max_length = 200)
    Culture                = models.CharField("Culture", max_length = 200)
    Organism_cultured      = models.CharField("Organism_cultured", max_length = 200)
    Respiration            = models.CharField("Respiration", max_length = 200)
    Electron_Donor         = models.TextField("Electron_Donor", max_length = 2000)
    Electron_Acceptor      = models.CharField("Electron_Acceptor", max_length = 200)
    Input                  = models.CharField("Input", max_length = 200)
    Nitrate_Removal_Rate   = models.CharField("Nitrate_Removal_Rate", max_length = 200)
    Denitrification_Rate   = models.CharField("Denitrification_Rate", max_length = 200)
    Microorganism_identified = models.TextField("Microorganism_identified", max_length = 2000)
    Molecular_Tools        = models.CharField("Molecular_Tools", max_length = 200)
    Major_Findings         = models.CharField("Major_Findings", max_length = 2000)
    Authors                = models.CharField("Authors", max_length = 200)
    Title                  = models.TextField("Title", max_length = 5000)
    Pubmed                 = models.CharField("Pubmed", max_length = 2000)
    Link                   = models.CharField("Link", max_length = 200)
    Abstract               = models.TextField("Abstract", max_length = 20000)
    
class MarineSystem(models.Model):
    Influent_Source_Type   = models.CharField("Influent_Source_Type", max_length = 200)
    Denitrification_System = models.CharField("Denitrification_System", max_length = 200)
    Denitrifying_Reactor   = models.CharField("Denitrifying_Reactor", max_length = 200)
    Medium                 = models.CharField("Medium", max_length = 200)
    Culture                = models.CharField("Culture", max_length = 200)
    Organism_cultured      = models.CharField("Organism_cultured", max_length = 200)
    Respiration            = models.CharField("Respiration", max_length = 200)
    Electron_Donor         = models.TextField("Electron_Donor", max_length = 2000)
    Electron_Acceptor      = models.CharField("Electron_Acceptor", max_length = 200)
    Input                  = models.CharField("Input", max_length = 200)
    Nitrate_Removal_Rate   = models.CharField("Nitrate_Removal_Rate", max_length = 200)
    Denitrification_Rate   = models.CharField("Denitrification_Rate", max_length = 200)
    Microorganism_identified = models.TextField("Microorganism_identified", max_length = 2000)
    Molecular_Tools        = models.CharField("Molecular_Tools", max_length = 200)
    Major_Findings         = models.CharField("Major_Findings", max_length = 2000)
    Authors                = models.CharField("Authors", max_length = 200)
    Title                  = models.TextField("Title", max_length = 5000)
    Pubmed                 = models.CharField("Pubmed", max_length = 2000)
    Link                   = models.CharField("Link", max_length = 200)
    Abstract               = models.TextField("Abstract", max_length = 20000)
    
class GoundwaterSystem(models.Model):
    Influent_Source_Type   = models.CharField("Influent_Source_Type", max_length = 200)
    Denitrification_System = models.CharField("Denitrification_System", max_length = 200)
    Denitrifying_Reactor   = models.CharField("Denitrifying_Reactor", max_length = 200)
    Medium                 = models.CharField("Medium", max_length = 200)
    Culture                = models.CharField("Culture", max_length = 200)
    Organism_cultured      = models.CharField("Organism_cultured", max_length = 200)
    Respiration            = models.CharField("Respiration", max_length = 200)
    Electron_Donor         = models.TextField("Electron_Donor", max_length = 2000)
    Electron_Acceptor      = models.CharField("Electron_Acceptor", max_length = 200)
    Input                  = models.CharField("Input", max_length = 200)
    Nitrate_Removal_Rate   = models.CharField("Nitrate_Removal_Rate", max_length = 200)
    Denitrification_Rate   = models.CharField("Denitrification_Rate", max_length = 200)
    Microorganism_identified = models.TextField("Microorganism_identified", max_length = 2000)
    Molecular_Tools        = models.CharField("Molecular_Tools", max_length = 200)
    Major_Findings         = models.CharField("Major_Findings", max_length = 2000)
    Authors                = models.CharField("Authors", max_length = 200)
    Title                  = models.TextField("Title", max_length = 5000)
    Pubmed                 = models.CharField("Pubmed", max_length = 2000)
    Link                   = models.CharField("Link", max_length = 200)
    Abstract               = models.TextField("Abstract", max_length = 20000)
    
class WetlandRiparianZones(models.Model):
    Influent_Source_Type   = models.CharField("Influent_Source_Type", max_length = 200)
    Denitrification_System = models.CharField("Denitrification_System", max_length = 200)
    Denitrifying_Reactor   = models.CharField("Denitrifying_Reactor", max_length = 200)
    Medium                 = models.CharField("Medium", max_length = 200)
    Culture                = models.CharField("Culture", max_length = 200)
    Organism_cultured      = models.CharField("Organism_cultured", max_length = 200)
    Respiration            = models.CharField("Respiration", max_length = 200)
    Electron_Donor         = models.TextField("Electron_Donor", max_length = 2000)
    Electron_Acceptor      = models.CharField("Electron_Acceptor", max_length = 200)
    Input                  = models.CharField("Input", max_length = 200)
    Nitrate_Removal_Rate   = models.CharField("Nitrate_Removal_Rate", max_length = 200)
    Denitrification_Rate   = models.CharField("Denitrification_Rate", max_length = 200)
    Microorganism_identified = models.TextField("Microorganism_identified", max_length = 2000)
    Molecular_Tools        = models.CharField("Molecular_Tools", max_length = 200)
    Major_Findings         = models.CharField("Major_Findings", max_length = 2000)
    Authors                = models.CharField("Authors", max_length = 200)
    Title                  = models.TextField("Title", max_length = 5000)
    Pubmed                 = models.CharField("Pubmed", max_length = 2000)
    Link                   = models.CharField("Link", max_length = 200)
    Abstract               = models.TextField("Abstract", max_length = 20000)
    
class SulphurRemoval(models.Model):
    Influent_Source_Type   = models.CharField("Influent_Source_Type", max_length = 200)
    Denitrification_System = models.CharField("Denitrification_System", max_length = 200)
    Denitrifying_Reactor   = models.CharField("Denitrifying_Reactor", max_length = 200)
    Medium                 = models.CharField("Medium", max_length = 200)
    Culture                = models.CharField("Culture", max_length = 200)
    Organism_cultured      = models.CharField("Organism_cultured", max_length = 200)
    Respiration            = models.CharField("Respiration", max_length = 200)
    Electron_Donor         = models.TextField("Electron_Donor", max_length = 2000)
    Nitrate_Removal_Rate   = models.CharField("Nitrate_Removal_Rate", max_length = 200)
    Denitrification_Rate   = models.CharField("Denitrification_Rate", max_length = 200)
    Major_Findings         = models.CharField("Major_Findings", max_length = 2000)
    Authors                = models.CharField("Authors", max_length = 200)
    Title                  = models.TextField("Title", max_length = 5000)
    Pubmed                 = models.CharField("Pubmed", max_length = 2000)
    Link                   = models.CharField("Link", max_length = 200)
    Abstract               = models.TextField("Abstract", max_length = 20000)