# Generated by Django 2.0 on 2020-06-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denitrifications_app', '0002_freshwatersystem_goundwatersystem_marinesystem_sulphurremoval_watertreatmentplant_wetlandriparianzon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshwatersystem',
            name='Electron_Donor',
            field=models.TextField(max_length=2000, verbose_name='Electron_Donor'),
        ),
        migrations.AlterField(
            model_name='goundwatersystem',
            name='Electron_Donor',
            field=models.TextField(max_length=2000, verbose_name='Electron_Donor'),
        ),
        migrations.AlterField(
            model_name='marinesystem',
            name='Electron_Donor',
            field=models.TextField(max_length=2000, verbose_name='Electron_Donor'),
        ),
        migrations.AlterField(
            model_name='sulphurremoval',
            name='Electron_Donor',
            field=models.TextField(max_length=2000, verbose_name='Electron_Donor'),
        ),
        migrations.AlterField(
            model_name='watertreatmentplant',
            name='Electron_Donor',
            field=models.TextField(max_length=2000, verbose_name='Electron_Donor'),
        ),
        migrations.AlterField(
            model_name='wetlandriparianzones',
            name='Electron_Donor',
            field=models.TextField(max_length=2000, verbose_name='Electron_Donor'),
        ),
    ]
